# clock
set_property PACKAGE_PIN Y18 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property PACKAGE_PIN K13 [get_ports reset] # which R?
set_property IOSTANDARD LVCMOS33 [get_ports reset]

# io_led_led
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[15]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[16]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[17]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[18]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[19]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[20]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[21]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[22]]
set_property IOSTANDARD LVCMOS33 [get_ports io_led_led[23]]
set_property PACKAGE_PIN A21 [get_ports io_led_led[0]]
set_property PACKAGE_PIN E22 [get_ports io_led_led[1]]
set_property PACKAGE_PIN D22 [get_ports io_led_led[2]]
set_property PACKAGE_PIN E21 [get_ports io_led_led[3]]
set_property PACKAGE_PIN D21 [get_ports io_led_led[4]]
set_property PACKAGE_PIN G21 [get_ports io_led_led[5]]
set_property PACKAGE_PIN G22 [get_ports io_led_led[6]]
set_property PACKAGE_PIN F21 [get_ports io_led_led[7]]
set_property PACKAGE_PIN J17 [get_ports io_led_led[8]]
set_property PACKAGE_PIN L14 [get_ports io_led_led[9]]
set_property PACKAGE_PIN L15 [get_ports io_led_led[10]]
set_property PACKAGE_PIN L16 [get_ports io_led_led[11]]
set_property PACKAGE_PIN K16 [get_ports io_led_led[12]]
set_property PACKAGE_PIN M15 [get_ports io_led_led[13]]
# 6 OR 8 ?
set_property PACKAGE_PIN M16 [get_ports io_led_led[14]]
set_property PACKAGE_PIN M17 [get_ports io_led_led[15]]
set_property PACKAGE_PIN N19 [get_ports io_led_led[16]]
set_property PACKAGE_PIN N20 [get_ports io_led_led[17]]
set_property PACKAGE_PIN M20 [get_ports io_led_led[18]]
set_property PACKAGE_PIN K13 [get_ports io_led_led[19]]
set_property PACKAGE_PIN K14 [get_ports io_led_led[20]]
set_property PACKAGE_PIN M13 [get_ports io_led_led[21]]
set_property PACKAGE_PIN L13 [get_ports io_led_led[22]]
set_property PACKAGE_PIN K17 [get_ports io_led_led[23]]



# switch
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[0]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[1]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[2]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[3]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[4]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[5]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[6]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[7]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[8]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[9]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[10]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[11]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[12]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[13]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[14]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[15]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[16]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[17]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[18]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[19]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[20]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[21]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[22]]
set_property IOSTANDARD LVCMOS33 [get_ports io_switch_switches[23]]
set_property PACKAGE_PIN W4 [get_ports io_switch_switches[0]]
set_property PACKAGE_PIN R4 [get_ports io_switch_switches[1]]
set_property PACKAGE_PIN T4 [get_ports io_switch_switches[2]]
set_property PACKAGE_PIN T5 [get_ports io_switch_switches[3]]
set_property PACKAGE_PIN U5 [get_ports io_switch_switches[4]]
set_property PACKAGE_PIN W6 [get_ports io_switch_switches[5]]
set_property PACKAGE_PIN W5 [get_ports io_switch_switches[6]]
set_property PACKAGE_PIN U6 [get_ports io_switch_switches[7]]
set_property PACKAGE_PIN V5 [get_ports io_switch_switches[8]]
set_property PACKAGE_PIN R6 [get_ports io_switch_switches[9]]
set_property PACKAGE_PIN T6 [get_ports io_switch_switches[10]]
set_property PACKAGE_PIN Y6 [get_ports io_switch_switches[11]]
set_property PACKAGE_PIN AA6 [get_ports io_switch_switches[12]]
set_property PACKAGE_PIN V7 [get_ports io_switch_switches[13]]
set_property PACKAGE_PIN AB7 [get_ports io_switch_switches[14]]
set_property PACKAGE_PIN AB6 [get_ports io_switch_switches[15]]
set_property PACKAGE_PIN V9 [get_ports io_switch_switches[16]]
set_property PACKAGE_PIN V8 [get_ports io_switch_switches[17]]
set_property PACKAGE_PIN AA8 [get_ports io_switch_switches[18]]
set_property PACKAGE_PIN AB8 [get_ports io_switch_switches[19]]
set_property PACKAGE_PIN Y8 [get_ports io_switch_switches[20]]
set_property PACKAGE_PIN Y7 [get_ports io_switch_switches[21]]
set_property PACKAGE_PIN W9 [get_ports io_switch_switches[22]]
set_property PACKAGE_PIN Y9 [get_ports io_switch_switch[23]]


# io_btn_button
set_property IOSTANDARD LVCMOS33 [get_ports io_btn_button[0]]
set_property IOSTANDARD LVCMOS33 [get_ports io_btn_button[1]]
set_property IOSTANDARD LVCMOS33 [get_ports io_btn_button[2]]
set_property IOSTANDARD LVCMOS33 [get_ports io_btn_button[3]]
set_property IOSTANDARD LVCMOS33 [get_ports io_btn_button[4]]
set_property PACKAGE_PIN R1 [get_ports io_btn_button[0]]
set_property PACKAGE_PIN P1 [get_ports io_btn_button[1]]
set_property PACKAGE_PIN P5 [get_ports io_btn_button[2]]
set_property PACKAGE_PIN P4 [get_ports io_btn_button[3]]
set_property PACKAGE_PIN P2 [get_ports io_btn_button[4]]


# rx
set_property IOSTANDARD LVCMOS33 [get_ports io_uart_rx]
set_property PACKAGE_PIN Y19 [get_ports io_uart_rx]
# tx
set_property IOSTANDARD LVCMOS33 [get_ports io_uart_tx]
set_property PACKAGE_PIN V18 [get_ports io_uart_tx]

#7seg
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_seg7[0]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_seg7[1]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_seg7[2]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_seg7[3]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_seg7[4]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_seg7[5]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_seg7[6]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_seg7[7]]
set_property PACKAGE_PIN E13 [get_ports io_seg7_seg7[0]]
set_property PACKAGE_PIN C15 [get_ports io_seg7_seg7[1]]
set_property PACKAGE_PIN C14 [get_ports io_seg7_seg7[2]]
set_property PACKAGE_PIN E17 [get_ports io_seg7_seg7[3]]
set_property PACKAGE_PIN F16 [get_ports io_seg7_seg7[4]]
set_property PACKAGE_PIN F14 [get_ports io_seg7_seg7[5]]
set_property PACKAGE_PIN F13 [get_ports io_seg7_seg7[6]]
set_property PACKAGE_PIN F15 [get_ports io_seg7_seg7[7]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_an[3]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_an[4]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_an[5]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_an[6]]
set_property IOSTANDARD LVCMOS33 [get_ports io_seg7_an[7]]
set_property PACKAGE_PIN C19 [get_ports io_seg7_an[0]]
set_property PACKAGE_PIN E19 [get_ports io_seg7_an[1]]
set_property PACKAGE_PIN D19 [get_ports io_seg7_an[2]]
set_property PACKAGE_PIN F18 [get_ports io_seg7_an[3]]
set_property PACKAGE_PIN E18 [get_ports io_seg7_an[4]]
set_property PACKAGE_PIN B20 [get_ports io_seg7_an[5]]
set_property PACKAGE_PIN A20 [get_ports io_seg7_an[6]]
set_property PACKAGE_PIN A18 [get_ports io_seg7_an[7]]

