set_property SRC_FILE_INFO {cfile:D:/ComputerScience/Projects/CPUdemo/generate/constraint2.xdc rfile:../../../../../constraint2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports clock]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports reset]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports {io_led_led[0]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E22 [get_ports {io_led_led[1]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D22 [get_ports {io_led_led[2]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E21 [get_ports {io_led_led[3]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {io_led_led[4]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G21 [get_ports {io_led_led[5]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports {io_led_led[6]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F21 [get_ports {io_led_led[7]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports {io_led_led[8]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {io_led_led[9]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {io_led_led[10]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports {io_led_led[11]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {io_led_led[12]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {io_led_led[13]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {io_led_led[14]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {io_led_led[15]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19 [get_ports {io_led_led[16]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports {io_led_led[17]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports {io_led_led[18]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports {io_led_led[19]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports {io_led_led[20]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports {io_led_led[21]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L13 [get_ports {io_led_led[22]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {io_led_led[23]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports {io_switch_switches[0]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports {io_switch_switches[1]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {io_switch_switches[2]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {io_switch_switches[3]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports {io_switch_switches[4]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {io_switch_switches[5]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {io_switch_switches[6]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {io_switch_switches[7]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {io_switch_switches[8]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {io_switch_switches[9]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {io_switch_switches[10]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports {io_switch_switches[11]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA6 [get_ports {io_switch_switches[12]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {io_switch_switches[13]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports {io_switch_switches[14]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports {io_switch_switches[15]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {io_switch_switches[16]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {io_switch_switches[17]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {io_switch_switches[18]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {io_switch_switches[19]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports {io_switch_switches[20]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports {io_switch_switches[21]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W9 [get_ports {io_switch_switches[22]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports {io_switch_switches[23]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {io_btn_button[0]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports {io_btn_button[1]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {io_btn_button[2]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {io_btn_button[3]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {io_btn_button[4]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports io_uart_rx]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports io_uart_tx]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {io_seg7_seg7[0]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {io_seg7_seg7[1]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {io_seg7_seg7[2]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {io_seg7_seg7[3]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports {io_seg7_seg7[4]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {io_seg7_seg7[5]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports {io_seg7_seg7[6]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {io_seg7_seg7[7]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports {io_seg7_an[0]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {io_seg7_an[1]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {io_seg7_an[2]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports {io_seg7_an[3]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {io_seg7_an[4]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {io_seg7_an[5]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {io_seg7_an[6]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {io_seg7_an[7]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clockSeparator/ip_clock/inst/clk_out2]]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {cpu/state/io_cpu_state[0]} {cpu/state/io_cpu_state[1]}]]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list clockSeparator/ip_clock/inst/clkfbout_buf_clk_wiz_0]]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list clockSeparator_reset]]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {cpu/memory/outRegisters/io_external_led_led[0]} {cpu/memory/outRegisters/io_external_led_led[1]} {cpu/memory/outRegisters/io_external_led_led[2]} {cpu/memory/outRegisters/io_external_led_led[3]} {cpu/memory/outRegisters/io_external_led_led[4]} {cpu/memory/outRegisters/io_external_led_led[5]} {cpu/memory/outRegisters/io_external_led_led[6]} {cpu/memory/outRegisters/io_external_led_led[7]} {cpu/memory/outRegisters/io_external_led_led[8]} {cpu/memory/outRegisters/io_external_led_led[9]} {cpu/memory/outRegisters/io_external_led_led[10]} {cpu/memory/outRegisters/io_external_led_led[11]} {cpu/memory/outRegisters/io_external_led_led[12]} {cpu/memory/outRegisters/io_external_led_led[13]} {cpu/memory/outRegisters/io_external_led_led[14]} {cpu/memory/outRegisters/io_external_led_led[15]} {cpu/memory/outRegisters/io_external_led_led[16]} {cpu/memory/outRegisters/io_external_led_led[17]} {cpu/memory/outRegisters/io_external_led_led[18]} {cpu/memory/outRegisters/io_external_led_led[19]} {cpu/memory/outRegisters/io_external_led_led[20]} {cpu/memory/outRegisters/io_external_led_led[21]} {cpu/memory/outRegisters/io_external_led_led[22]} {cpu/memory/outRegisters/io_external_led_led[23]} {cpu/memory/outRegisters/io_external_led_led[24]} {cpu/memory/outRegisters/io_external_led_led[25]} {cpu/memory/outRegisters/io_external_led_led[26]} {cpu/memory/outRegisters/io_external_led_led[27]} {cpu/memory/outRegisters/io_external_led_led[28]} {cpu/memory/outRegisters/io_external_led_led[29]} {cpu/memory/outRegisters/io_external_led_led[30]} {cpu/memory/outRegisters/io_external_led_led[31]}]]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {cpu/memory/outRegisters/io_mem_write_data[0]} {cpu/memory/outRegisters/io_mem_write_data[1]} {cpu/memory/outRegisters/io_mem_write_data[2]} {cpu/memory/outRegisters/io_mem_write_data[3]} {cpu/memory/outRegisters/io_mem_write_data[4]} {cpu/memory/outRegisters/io_mem_write_data[5]} {cpu/memory/outRegisters/io_mem_write_data[6]} {cpu/memory/outRegisters/io_mem_write_data[7]} {cpu/memory/outRegisters/io_mem_write_data[8]} {cpu/memory/outRegisters/io_mem_write_data[9]} {cpu/memory/outRegisters/io_mem_write_data[10]} {cpu/memory/outRegisters/io_mem_write_data[11]} {cpu/memory/outRegisters/io_mem_write_data[12]} {cpu/memory/outRegisters/io_mem_write_data[13]} {cpu/memory/outRegisters/io_mem_write_data[14]} {cpu/memory/outRegisters/io_mem_write_data[15]} {cpu/memory/outRegisters/io_mem_write_data[16]} {cpu/memory/outRegisters/io_mem_write_data[17]} {cpu/memory/outRegisters/io_mem_write_data[18]} {cpu/memory/outRegisters/io_mem_write_data[19]} {cpu/memory/outRegisters/io_mem_write_data[20]} {cpu/memory/outRegisters/io_mem_write_data[21]} {cpu/memory/outRegisters/io_mem_write_data[22]} {cpu/memory/outRegisters/io_mem_write_data[23]} {cpu/memory/outRegisters/io_mem_write_data[24]} {cpu/memory/outRegisters/io_mem_write_data[25]} {cpu/memory/outRegisters/io_mem_write_data[26]} {cpu/memory/outRegisters/io_mem_write_data[27]} {cpu/memory/outRegisters/io_mem_write_data[28]} {cpu/memory/outRegisters/io_mem_write_data[29]} {cpu/memory/outRegisters/io_mem_write_data[30]} {cpu/memory/outRegisters/io_mem_write_data[31]}]]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {cpu/memory/io_data_addr[0]} {cpu/memory/io_data_addr[1]} {cpu/memory/io_data_addr[2]} {cpu/memory/io_data_addr[3]} {cpu/memory/io_data_addr[4]} {cpu/memory/io_data_addr[5]} {cpu/memory/io_data_addr[6]} {cpu/memory/io_data_addr[7]} {cpu/memory/io_data_addr[8]} {cpu/memory/io_data_addr[9]} {cpu/memory/io_data_addr[10]} {cpu/memory/io_data_addr[11]} {cpu/memory/io_data_addr[12]} {cpu/memory/io_data_addr[13]} {cpu/memory/io_data_addr[14]} {cpu/memory/io_data_addr[15]} {cpu/memory/io_data_addr[16]} {cpu/memory/io_data_addr[17]} {cpu/memory/io_data_addr[18]} {cpu/memory/io_data_addr[19]} {cpu/memory/io_data_addr[20]} {cpu/memory/io_data_addr[21]} {cpu/memory/io_data_addr[22]} {cpu/memory/io_data_addr[23]} {cpu/memory/io_data_addr[24]} {cpu/memory/io_data_addr[25]} {cpu/memory/io_data_addr[26]} {cpu/memory/io_data_addr[27]} {cpu/memory/io_data_addr[28]} {cpu/memory/io_data_addr[29]} {cpu/memory/io_data_addr[30]} {cpu/memory/io_data_addr[31]}]]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {cpu/memory/io_ins_addr[0]} {cpu/memory/io_ins_addr[1]} {cpu/memory/io_ins_addr[2]} {cpu/memory/io_ins_addr[3]} {cpu/memory/io_ins_addr[4]} {cpu/memory/io_ins_addr[5]} {cpu/memory/io_ins_addr[6]} {cpu/memory/io_ins_addr[7]} {cpu/memory/io_ins_addr[8]} {cpu/memory/io_ins_addr[9]} {cpu/memory/io_ins_addr[10]} {cpu/memory/io_ins_addr[11]} {cpu/memory/io_ins_addr[12]} {cpu/memory/io_ins_addr[13]} {cpu/memory/io_ins_addr[14]} {cpu/memory/io_ins_addr[15]} {cpu/memory/io_ins_addr[16]} {cpu/memory/io_ins_addr[17]} {cpu/memory/io_ins_addr[18]} {cpu/memory/io_ins_addr[19]} {cpu/memory/io_ins_addr[20]} {cpu/memory/io_ins_addr[21]} {cpu/memory/io_ins_addr[22]} {cpu/memory/io_ins_addr[23]} {cpu/memory/io_ins_addr[24]} {cpu/memory/io_ins_addr[25]} {cpu/memory/io_ins_addr[26]} {cpu/memory/io_ins_addr[27]} {cpu/memory/io_ins_addr[28]} {cpu/memory/io_ins_addr[29]} {cpu/memory/io_ins_addr[30]} {cpu/memory/io_ins_addr[31]}]]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {cpu/memory/io_ins_out[0]} {cpu/memory/io_ins_out[1]} {cpu/memory/io_ins_out[2]} {cpu/memory/io_ins_out[3]} {cpu/memory/io_ins_out[4]} {cpu/memory/io_ins_out[5]} {cpu/memory/io_ins_out[6]} {cpu/memory/io_ins_out[7]} {cpu/memory/io_ins_out[8]} {cpu/memory/io_ins_out[9]} {cpu/memory/io_ins_out[10]} {cpu/memory/io_ins_out[11]} {cpu/memory/io_ins_out[12]} {cpu/memory/io_ins_out[13]} {cpu/memory/io_ins_out[14]} {cpu/memory/io_ins_out[15]} {cpu/memory/io_ins_out[16]} {cpu/memory/io_ins_out[17]} {cpu/memory/io_ins_out[18]} {cpu/memory/io_ins_out[19]} {cpu/memory/io_ins_out[20]} {cpu/memory/io_ins_out[21]} {cpu/memory/io_ins_out[22]} {cpu/memory/io_ins_out[23]} {cpu/memory/io_ins_out[24]} {cpu/memory/io_ins_out[25]} {cpu/memory/io_ins_out[26]} {cpu/memory/io_ins_out[27]} {cpu/memory/io_ins_out[28]} {cpu/memory/io_ins_out[29]} {cpu/memory/io_ins_out[30]} {cpu/memory/io_ins_out[31]}]]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {cpu/memory/io_data_write[0]} {cpu/memory/io_data_write[1]} {cpu/memory/io_data_write[2]} {cpu/memory/io_data_write[3]} {cpu/memory/io_data_write[4]} {cpu/memory/io_data_write[5]} {cpu/memory/io_data_write[6]} {cpu/memory/io_data_write[7]} {cpu/memory/io_data_write[8]} {cpu/memory/io_data_write[9]} {cpu/memory/io_data_write[10]} {cpu/memory/io_data_write[11]} {cpu/memory/io_data_write[12]} {cpu/memory/io_data_write[13]} {cpu/memory/io_data_write[14]} {cpu/memory/io_data_write[15]} {cpu/memory/io_data_write[16]} {cpu/memory/io_data_write[17]} {cpu/memory/io_data_write[18]} {cpu/memory/io_data_write[19]} {cpu/memory/io_data_write[20]} {cpu/memory/io_data_write[21]} {cpu/memory/io_data_write[22]} {cpu/memory/io_data_write[23]} {cpu/memory/io_data_write[24]} {cpu/memory/io_data_write[25]} {cpu/memory/io_data_write[26]} {cpu/memory/io_data_write[27]} {cpu/memory/io_data_write[28]} {cpu/memory/io_data_write[29]} {cpu/memory/io_data_write[30]} {cpu/memory/io_data_write[31]}]]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {cpu/pc/io_addr[0]} {cpu/pc/io_addr[1]} {cpu/pc/io_addr[2]} {cpu/pc/io_addr[3]} {cpu/pc/io_addr[4]} {cpu/pc/io_addr[5]} {cpu/pc/io_addr[6]} {cpu/pc/io_addr[7]} {cpu/pc/io_addr[8]} {cpu/pc/io_addr[9]} {cpu/pc/io_addr[10]} {cpu/pc/io_addr[11]} {cpu/pc/io_addr[12]} {cpu/pc/io_addr[13]} {cpu/pc/io_addr[14]} {cpu/pc/io_addr[15]} {cpu/pc/io_addr[16]} {cpu/pc/io_addr[17]} {cpu/pc/io_addr[18]} {cpu/pc/io_addr[19]} {cpu/pc/io_addr[20]} {cpu/pc/io_addr[21]} {cpu/pc/io_addr[22]} {cpu/pc/io_addr[23]} {cpu/pc/io_addr[24]} {cpu/pc/io_addr[25]} {cpu/pc/io_addr[26]} {cpu/pc/io_addr[27]} {cpu/pc/io_addr[28]} {cpu/pc/io_addr[29]} {cpu/pc/io_addr[30]} {cpu/pc/io_addr[31]}]]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {cpu/regs/io_rs2_val[0]} {cpu/regs/io_rs2_val[1]} {cpu/regs/io_rs2_val[2]} {cpu/regs/io_rs2_val[3]} {cpu/regs/io_rs2_val[4]} {cpu/regs/io_rs2_val[5]} {cpu/regs/io_rs2_val[6]} {cpu/regs/io_rs2_val[7]} {cpu/regs/io_rs2_val[8]} {cpu/regs/io_rs2_val[9]} {cpu/regs/io_rs2_val[10]} {cpu/regs/io_rs2_val[11]} {cpu/regs/io_rs2_val[12]} {cpu/regs/io_rs2_val[13]} {cpu/regs/io_rs2_val[14]} {cpu/regs/io_rs2_val[15]} {cpu/regs/io_rs2_val[16]} {cpu/regs/io_rs2_val[17]} {cpu/regs/io_rs2_val[18]} {cpu/regs/io_rs2_val[19]} {cpu/regs/io_rs2_val[20]} {cpu/regs/io_rs2_val[21]} {cpu/regs/io_rs2_val[22]} {cpu/regs/io_rs2_val[23]} {cpu/regs/io_rs2_val[24]} {cpu/regs/io_rs2_val[25]} {cpu/regs/io_rs2_val[26]} {cpu/regs/io_rs2_val[27]} {cpu/regs/io_rs2_val[28]} {cpu/regs/io_rs2_val[29]} {cpu/regs/io_rs2_val[30]} {cpu/regs/io_rs2_val[31]}]]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {cpu/regs/io_rs1_val[0]} {cpu/regs/io_rs1_val[1]} {cpu/regs/io_rs1_val[2]} {cpu/regs/io_rs1_val[3]} {cpu/regs/io_rs1_val[4]} {cpu/regs/io_rs1_val[5]} {cpu/regs/io_rs1_val[6]} {cpu/regs/io_rs1_val[7]} {cpu/regs/io_rs1_val[8]} {cpu/regs/io_rs1_val[9]} {cpu/regs/io_rs1_val[10]} {cpu/regs/io_rs1_val[11]} {cpu/regs/io_rs1_val[12]} {cpu/regs/io_rs1_val[13]} {cpu/regs/io_rs1_val[14]} {cpu/regs/io_rs1_val[15]} {cpu/regs/io_rs1_val[16]} {cpu/regs/io_rs1_val[17]} {cpu/regs/io_rs1_val[18]} {cpu/regs/io_rs1_val[19]} {cpu/regs/io_rs1_val[20]} {cpu/regs/io_rs1_val[21]} {cpu/regs/io_rs1_val[22]} {cpu/regs/io_rs1_val[23]} {cpu/regs/io_rs1_val[24]} {cpu/regs/io_rs1_val[25]} {cpu/regs/io_rs1_val[26]} {cpu/regs/io_rs1_val[27]} {cpu/regs/io_rs1_val[28]} {cpu/regs/io_rs1_val[29]} {cpu/regs/io_rs1_val[30]} {cpu/regs/io_rs1_val[31]}]]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list cpu/memory/outRegisters/io_mem_write]]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list cpu/memory/io_write_data]]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clkfbout_buf_clk_wiz_0]
