package integrate

import Generate.Top
import chiseltest._
import org.scalatest._
import org.scalatest.matchers.should.Matchers
import utils.InsUtils._
import chisel3._

class software1Test extends FlatSpec with ChiselScalatestTester with Matchers {
  behavior of "Software1 Test"
  /* the following tests are for the software1, assembly code can be found in software */

  it should "correctly initialize the data address" in {
    load_instructions("software1.txt")
    test(new Top) { total =>
      run_instructions(total, 10)
      checkRegsInTop(total, 10, "h_ff_ff_ff_00".U) // led
      checkRegsInTop(total, 11, "h_ff_ff_ff_04".U) // btn
      checkRegsInTop(total, 12, "h_ff_ff_ff_08".U) // swi
      checkRegsInTop(total, 13, "h_ff_ff_ff_0c".U) // 7seg
      checkRegsInTop(total, 14, "h_70_00_00".U) // mask
    }
  }

  it should "correctly initialize the data address: final" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 20)
      checkRegsInTop(total, 10, "h_ff_ff_ff_00".U) // led
      checkRegsInTop(total, 11, "h_ff_ff_ff_04".U) // btn
      checkRegsInTop(total, 12, "h_ff_ff_ff_08".U) // swi
      checkRegsInTop(total, 13, "h_ff_ff_ff_0c".U) // 7seg
      checkRegsInTop(total, 14, "h_70_00_00".U) // mask
      checkRegsInTop(total, 16, "h_00_01_ff_fc".U)
    }
  }

  it should "correctly initialize the data address : t1" in {
    load_instructions("software1_t1.txt")
    test(new Top) { total =>
      run_instructions(total, 10)
      checkRegsInTop(total, 10, "h_ff_ff_ff_00".U) // led
      checkRegsInTop(total, 11, "h_ff_ff_ff_04".U) // btn
      checkRegsInTop(total, 12, "h_ff_ff_ff_08".U) // swi
      checkRegsInTop(total, 13, "h_ff_ff_ff_0c".U) // 7seg
      checkRegsInTop(total, 14, "h_e0_00_00".U) // mask
    }
  }

  it should "correctly initialize the data address : t2" in {
    load_instructions("software1_t2.txt")
    test(new Top) { total =>
      run_instructions(total, 10)
      checkRegsInTop(total, 10, "h_ff_ff_ff_00".U) // led
      checkRegsInTop(total, 11, "h_ff_ff_ff_04".U) // btn
      checkRegsInTop(total, 12, "h_ff_ff_ff_08".U) // swi
      checkRegsInTop(total, 13, "h_ff_ff_ff_0c".U) // 7seg
      checkRegsInTop(total, 14, "h_e0_00_00".U) // mask
    }
  }
//
//  it should "jump to the correct place1 : stay in the cycle if no correct input in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place2 : jump to case 0 if input 0 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_00_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ab_00".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_cd_ef".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ab_ef".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ab_ef".U)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place3 : jump to case 1 if input 1 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_10_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place4 : jump to case 2 if input 2 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 29, "h_cd".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place5 : jump to case 3 if input 3 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_10_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_30_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      checkRegsInTop(total, 31, 0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place5 : jump to case 3 if input 3 in button _ test jump" in {
//    load_instructions("software1_t1.txt") // 这个和原先的的区别是 case3 条件的 beq 变成了 bne
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 50)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_40_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_60_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      checkRegsInTop(total, 31, 1.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place5.1 : jump to case 3 if input 3 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_10_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_05_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_05".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_05".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_05".U)
//      checkRegsInTop(total, 29, "h_05".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_30_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_05".U)
//      checkRegsInTop(total, 29, "h_05".U)
//      checkRegsInTop(total, 31, 1.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place6 : jump to case 4 if input 4 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_10_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_40_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 31, 1.U)
//      total.io.led.led.expect(1.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place7 : jump to case 5 if input 5 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_10_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 29, "h_cd".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_50_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      checkRegsInTop(total, 31, 0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place7.2 : jump to case 5 if input 5 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_10_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_12_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_12".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_02".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 29, "h_2".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_50_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_12".U)
//      checkRegsInTop(total, 29, "h_2".U)
//      checkRegsInTop(total, 31, 1.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place8 : jump to case 6 if input 6 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_10_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 29, "h_cd".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_60_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      checkRegsInTop(total, 31, 0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }
//
//  it should "jump to the correct place9 : jump to case 7 if input 7 in button" in {
//    load_instructions("software1.txt")
//    test(new Top) { total =>
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_10_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_20_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      total.io.switch.switches.poke("h_00_ab_cd".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 29, "h_cd".U)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//      total.io.switch.switches.poke("h_70_12_34".U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(4.U)
//      run_instructions(total, 30)
//      total.io.btn.button.poke(0.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
//      checkRegsInTop(total, 29, "h_cd".U)
//      checkRegsInTop(total, 31, 1.U)
//      run_instructions(total, 30)
//      checkRegsInTop(total, 15, 0.U)
//    }
//  }

  it should "perform good in case 0" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_00_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_cd_00".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_24_ef".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_cd_ef".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_cd_ef".U)
      checkRegsInTop(total, 15, 0.U)
    }
  }

  it should "perform good in case 1" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_cd".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }
  it should "perform good in case 1 - 2" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_1d".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_1d".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }

  it should "perform good in case 2" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_ef".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 29, "h_ef".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }
  it should "perform good in case 2 - 2" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_1d".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 29, "h_1d".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }

  // beq
  it should "perform good in case 3" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_ab".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_30_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      checkRegsInTop(total, 31, 0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }
  it should "perform good in case 3 twice" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_12".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_12".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      checkRegsInTop(total, 29, "h_12".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_30_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      checkRegsInTop(total, 29, "h_12".U)
      checkRegsInTop(total, 31, 1.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_cd".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_30_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_cd".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_cd".U)
      checkRegsInTop(total, 29, "h_12".U)
      checkRegsInTop(total, 31, 0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }

  // blt
  it should "perform good in case 4" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_ab".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_40_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      checkRegsInTop(total, 31, 1.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }
  it should "perform good in case 4 twice" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_ab".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_34".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_40_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_34".U)
      checkRegsInTop(total, 31, 1.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_3f".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_40_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      checkRegsInTop(total, 29, "h_34".U)
      checkRegsInTop(total, 31, 0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }

  // bge
  it should "perform good in case 5" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_ab".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_50_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      checkRegsInTop(total, 31, 0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }
  it should "perform good in case 5 twice" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_3f".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      checkRegsInTop(total, 29, "h_34".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_50_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      checkRegsInTop(total, 29, "h_34".U)
      checkRegsInTop(total, 31, 1.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_ab".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_50_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_34".U)
      checkRegsInTop(total, 31, 0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }

  // bltu
  it should "perform good in case 6" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_ab".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_60_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      checkRegsInTop(total, 31, 0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }
  it should "perform good in case 6 twice" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_12".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      checkRegsInTop(total, 29, "h_34".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_60_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      checkRegsInTop(total, 29, "h_34".U)
      checkRegsInTop(total, 31, 1.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_80".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_80".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_60_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_80".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_80".U)
      checkRegsInTop(total, 29, "h_34".U)
      checkRegsInTop(total, 31, 0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }

  // bgeu
  it should "perform good in case 7" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_ab".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_70_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_ff_ff_ff_ab".U)
      checkRegsInTop(total, 29, "h_cd".U)
      checkRegsInTop(total, 31, 1.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }
  it should "perform good in case 7 twice" in {
    load_instructions("software1_final.txt")
    test(new Top) { total =>
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_cd".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_3f".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_20_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_ab_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      checkRegsInTop(total, 29, "h_34".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_70_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_3f".U)
      checkRegsInTop(total, 29, "h_34".U)
      checkRegsInTop(total, 31, 1.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_10_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      total.io.switch.switches.poke("h_00_cd_12".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)

      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
      total.io.switch.switches.poke("h_70_12_34".U)
      run_instructions(total, 30)
      total.io.btn.button.poke(4.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      total.io.btn.button.poke(0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 28, "h_12".U)
      checkRegsInTop(total, 29, "h_34".U)
      checkRegsInTop(total, 31, 0.U)
      run_instructions(total, 30)
      checkRegsInTop(total, 15, 0.U)
    }
  }
}
